export const columns = [
  {
    Header: 'Id',
    accessor: 'employeId',
  },
  {
    Header: 'Imię',
    accessor: 'employeFirstName',
  },
  {
    Header: 'Nazwisko',
    accessor: 'employeLastName',
  },
  {
    Header: 'Wiek',
    accessor: 'employeAge',
  },
  {
    Header: 'Stanowisko',
    accessor: 'employePosition',
  },
  {
    Header: 'Dział',
    accessor: 'employeDep',
  },
  {
    Header: 'Pensja',
    accessor: 'employeSalary',
  },
];

export const exampleData = [
  {
    employeId: 13456,
    employeFirstName: 'Jan',
    employeLastName: 'Kowalski',
    employeAge: 38,
    employePosition: 'Kierownik IT',
    employeDep: 'IT',
    employeSalary: 9000,
  },
  {
    employeId: 13457,
    employeFirstName: 'Matylda',
    employeLastName: 'Nowak',
    employeAge: 26,
    employePosition: 'Recepcjonistka',
    employeDep: 'Administracja',
    employeSalary: 4500,
  },
  {
    employeId: 13458,
    employeFirstName: 'Rafał',
    employeLastName: 'Ratajczyk',
    employeAge: 29,
    employePosition: 'Specjalista IT',
    employeDep: 'IT',
    employeSalary: 6000,
  },
  {
    employeId: 13459,
    employeFirstName: 'Sebastian',
    employeLastName: 'Michniewicz',
    employeAge: 26,
    employePosition: 'Specjalista IT',
    employeDep: 'IT',
    employeSalary: 7000,
  },
  {
    employeId: 13460,
    employeFirstName: 'Anna',
    employeLastName: 'Rak',
    employeAge: 44,
    employePosition: 'Księgowa',
    employeDep: 'Finansowy',
    employeSalary: 7500,
  },
  {
    employeId: 13461,
    employeFirstName: 'Magdalena',
    employeLastName: 'Jakicka',
    employeAge: 32,
    employePosition: 'Specjalista ds. Marketingu',
    employeDep: 'Marketing',
    employeSalary: 5000,
  },
  {
    employeId: 13462,
    employeFirstName: 'Justyna',
    employeLastName: 'Patucka',
    employeAge: 36,
    employePosition: 'Kierownik Marketingu',
    employeDep: 'Marketing',
    employeSalary: 8500,
  },
  {
    employeId: 13463,
    employeFirstName: 'Jacek',
    employeLastName: 'Tomczuk',
    employeAge: 52,
    employePosition: 'Technik',
    employeDep: 'Techniczny',
    employeSalary: 5000,
  },
  {
    employeId: 13464,
    employeFirstName: 'Zofia',
    employeLastName: 'Tarczycka',
    employeAge: 36,
    employePosition: 'Starsza Księgowa',
    employeDep: 'Finansowy',
    employeSalary: 13000,
  },
  {
    employeId: 13465,
    employeFirstName: 'Maciej',
    employeLastName: 'Kucharski',
    employeAge: 25,
    employePosition: 'Młodszy Programista',
    employeDep: 'Finansowy',
    employeSalary: 5000,
  },
  {
    employeId: 13466,
    employeFirstName: 'Krzysztof',
    employeLastName: 'Karczyński',
    employeAge: 42,
    employePosition: 'Dyrektor Techniczny',
    employeDep: 'Techniczny',
    employeSalary: 11000,
  },
];
